Feat/migrate gdpr
santiment/san-webkit pull request #205
Opened 2024-11-13 12:01 UTC by serafim-san

2024-11-13 12:36 UTC, serafim-san commented on src/stories/Design System - App UI/Gdpr/index.svelte
> +    if (window.onGdprAccept) window.onGdprAccept()
I moved the analytics logic and policy update outside, removing side effects from the component for better readability and reusability

2024-11-24 20:17 UTC, DmitriVanGuard commented on src/lib/analytics/events/onboarding.ts
> +    source_url: window.location.href,
```suggestion
```

2024-11-24 20:22 UTC, DmitriVanGuard requested changes

2024-11-24 20:22 UTC, DmitriVanGuard commented on src/lib/utils/fn.ts
> +}
Use rxjs debounce in this case

2024-11-24 20:22 UTC, DmitriVanGuard commented on src/stories/Design System - App UI/LoginForm/Gdpr.svelte
> +    <Gdpr currentUser={currentUser.currentUser.$$} {onAccept} />
Gdpr should use customer ctx inside its component

2024-11-24 20:22 UTC, DmitriVanGuard commented on src/lib/ui/app/LoginForm/api.ts
> +}))
Pass values directly to schema

2024-11-24 20:22 UTC, DmitriVanGuard commented on src/lib/ui/app/LoginForm/Gdpr.svelte
> +      .then(() => mutateGdpr(Query)({ privacyPolicyAccepted: true }))
Failed username change should cancel whole promise chain.

2024-11-24 20:22 UTC, DmitriVanGuard commented on src/lib/ui/app/LoginForm/Gdpr.svelte
> +        currentUser.privacyPolicyAccepted = true
Reload customer instead of direct mutation

2024-12-17 10:57 UTC, DmitriVanGuard approved these changes

2024-12-17 10:58 UTC, merged