Pricing page update
santiment/san-webkit pull request #33
Opened 2022-06-27 09:50 UTC by Woafflation

Added Free plan
UI fixe
<img width="330" alt="Снимок экрана 2022-06-27 в 12 47 11" src="https://user-images.githubusercontent.com/46782114/175913956-bfa5592f-e3d6-4b3f-bf77-f075c661cf92.png">
<img width="859" alt="Снимок экрана 2022-06-27 в 12 47 52" src="https://user-images.githubusercontent.com/46782114/175913960-3bfd9a2c-bdaa-48a5-a7a3-63d13601a7aa.png">
<img width="1315" alt="Снимок экрана 2022-06-27 в 12 48 21" src="https://user-images.githubusercontent.com/46782114/175913969-b815e65a-1bce-4245-a65a-bda9d21c4dc8.png">
<img width="1315" alt="Снимок экрана 2022-06-27 в 12 49 19" src="https://user-images.githubusercontent.com/46782114/175913972-a569f46d-464e-485e-bd56-9a32d9c7c761.png">
s

2022-06-27 11:34 UTC, DmitriVanGuard requested changes

2022-06-27 11:34 UTC, DmitriVanGuard commented on src/ui/Pricing/Comparison/Feature.svelte
> +      <div slot="tooltip" class="description body-3">{@html description}</div>
`body-3` is inherited from the body and applied by default

2022-06-27 11:34 UTC, DmitriVanGuard commented on src/ui/Pricing/Comparison/index.svelte
> +  <FeaturesToggle bind:active={isShowLess} onClick={showMoreFeatures} />
1. Name is misleading and vaguely represent what this component does. Maybe, we can name it something like `<MoreFeaturesButton />`?
2. Use `bind` directive -> `bind:isShowingMore`

2022-06-27 11:34 UTC, DmitriVanGuard commented on src/ui/Pricing/Comparison/index.svelte
> +  export let isShowLess = true
```suggestion
  export let isShowingMore = false
```

2022-06-27 11:34 UTC, DmitriVanGuard commented on src/ui/Pricing/Comparison/FeaturesToggle.svelte
> +  export let active = false
```suggestion
  export let isShowingMore = false
```

2022-06-27 11:34 UTC, DmitriVanGuard commented on src/ui/Pricing/Comparison/FeaturesToggle.svelte
> +</div>
```suggestion
<button class="btn btn--accent row hv-center" class:more={isShowingMore} on:click={() => (isShowingMore = !isShowingMore)}>
    Show {isShowingMore ? 'less' : 'more'} features
    <Svg id="arrow-down" w="10" h="5.5" class="$style.arrow mrg-m rgm--l" />
</button>
```

2022-06-27 11:34 UTC, DmitriVanGuard commented on src/ui/Pricing/Comparison/FeaturesToggle.svelte
> +  }
```suggestion
 button {
   padding: 12px;
   --bg-hover: var(--porcelain);
 }
 
 .more {
   --rotate: 180deg;
 }
 
 .arrow {
   transform: rotate(var(--rotate));
 }
```

2022-06-27 11:34 UTC, DmitriVanGuard commented on src/ui/Pricing/Comparison/Plan.svelte
> +  $: ({ name: planName } = plan)
```suggestion
  $: ({ name } = plan)
```

2022-06-27 11:34 UTC, DmitriVanGuard commented on src/ui/Pricing/Comparison/comapre.ts
> +  'Bi-weekly report': true,
This is a default value
```suggestion
```

2022-06-27 11:34 UTC, DmitriVanGuard commented on src/ui/Pricing/Comparison/comapre.ts
> +  'Bi-weekly report': true,
These are default values

```suggestion
```

2022-06-28 13:36 UTC, Woafflation commented on src/ui/Pricing/Comparison/Feature.svelte
> +      <div slot="tooltip" class="description body-3">{@html description}</div>
![Снимок экрана 2022-06-28 в 15 52 13](https://user-images.githubusercontent.com/46782114/176192368-e2f10358-4c49-44d9-afee-0f06e8b5f5b3.png)
![Снимок экрана 2022-06-28 в 15 52 20](https://user-images.githubusercontent.com/46782114/176192374-70814eb3-bf81-47d9-b2f0-b3da9a6cee8b.png)

Have to manually apply it

2022-06-29 13:11 UTC, DmitriVanGuard requested changes

2022-06-29 13:11 UTC, DmitriVanGuard commented on src/styles/buttons.css
> +}
Accent color should depend on the `--accent` variable as it does in the [`.c-accent` class](https://github.com/santiment/san-webkit/blob/master/src/styles/text.css#L94-L96)

2022-06-29 13:11 UTC, DmitriVanGuard commented on src/ui/Pricing/Comparison/Table.svelte
> +  $: tableItems = filterTableCompareItems(plans, isShowingMore)
Reactive statements should come before the function declarations
```suggestion
  $: tableItems = filterTableCompareItems(plans, isShowingMore)
  
  function filterTableCompareItems(items, shouldFilter) {
    if (shouldFilter) {
      return COMPARE_TABLE.slice(0, 7)
    }

    return COMPARE_TABLE
  }
```

2022-06-29 13:11 UTC, DmitriVanGuard commented on src/ui/Pricing/PlanButton.svelte
> +  }
Duplicate of the `btn--green` class

2022-07-06 07:50 UTC, DmitriVanGuard requested changes

2022-07-06 14:53 UTC, merged