link-pointer class added to links inside text
santiment/san-webkit pull request #55
Opened 2022-09-16 09:51 UTC by peratik

https://www.notion.so/santiment/Link-buttons-updates-ddb3cd3c912341a880e46a17b302bd35

2022-09-16 13:40 UTC, DmitriVanGuard requested changes

2022-09-16 13:40 UTC, DmitriVanGuard commented on src/ui/CookiesPopup.svelte
> +      <a href="https://santiment.net/cookies/" target="_blank" class="c-accent link-pointer"
`c-accent` is redundant

2022-09-16 13:40 UTC, DmitriVanGuard commented on src/ui/LoginPrompt/Section.svelte
> +      <a href={bottomHref} class="btn link-pointer" sapper:prefetch>{bottomAction}</a>
`btn` is redundant

2022-09-16 13:40 UTC, DmitriVanGuard commented on src/ui/LoginPrompt/Metamask.svelte
> +    <a href="https://metamask.io/#how-it-works" class="btn link-pointer">How Metamask works?</a>
`btn` is redundant

2022-09-16 13:40 UTC, DmitriVanGuard commented on src/ui/ManageCookiesDialog/index.svelte
> +    site. <a href="https://santiment.net/cookies/" target="_blank" class="c-accent link-pointer"
`c-accent` is redundant

2022-09-16 13:40 UTC, DmitriVanGuard commented on src/ui/Pricing/SubscriptionSettings/SubscriptionCard/PlanCard.svelte
> +        class="btn-0 link-pointer"
`btn-0` is redundant

2022-09-16 13:40 UTC, DmitriVanGuard commented on src/ui/Pricing/SubscriptionSettings/SubscriptionCard/UserPlanCard.svelte
> +        class="btn-0 link-pointer"
`btn-0` is redundant

2022-09-16 13:40 UTC, DmitriVanGuard commented on src/ui/Products/Products.svelte
> +        class="btn-0 link-pointer"
`btn-0` is redundant

2022-09-19 07:01 UTC, DmitriVanGuard requested changes

2022-09-19 07:04 UTC, peratik commented on src/ui/LoginPrompt/Section.svelte
> +      <a href={bottomHref} class="link-pointer" sapper:prefetch>{bottomAction}</a>
There is another `a` tag:

2022-09-19 07:04 UTC, peratik commented on src/ui/LoginPrompt/Section.svelte
> +      <a href={bottomHref} class="link-pointer" sapper:prefetch>{bottomAction}</a>
```
  {#if $IsMobile}
    <a href="/" class="close btn"><Svg id="close" w="16" /></a>
  {/if}
```

2022-09-19 07:05 UTC, peratik commented on src/ui/PaymentDialog/Banner.svelte
> +      touch with <button class="btn c-accent link-pointer" on:click={showIntercom}
1. button links also included

2022-09-19 07:07 UTC, peratik commented on src/ui/PaymentDialog/Banner.svelte
> +      touch with <button class="btn c-accent link-pointer" on:click={showIntercom}
2. Fixed

2022-09-19 07:09 UTC, peratik commented on src/ui/LoginPrompt/Section.svelte
> +      <a href={bottomHref} class="link-pointer" sapper:prefetch>{bottomAction}</a>
Fixed

2022-09-20 07:36 UTC, DmitriVanGuard approved these changes

2022-09-20 07:38 UTC, merged