PromoSanTokenBanner added
santiment/san-webkit pull request #56
Opened 2022-10-07 09:21 UTC by peratik

https://www.notion.so/santiment/Promo-San-token-banner-on-the-Pricing-page-86cb14bedff84f518f54950efd4447a7

- `PromoSanTokenBanner` component added
- `underplans` slot added to easily set without chaning san-webkit repo

2022-10-07 10:04 UTC, DmitriVanGuard commented on src/ui/Pricing/Page/PromoSanTokenBanner.svelte
> +      full PRO access.<br />
What is the point of the `<br />`

2022-10-07 10:27 UTC, peratik commented on src/ui/Pricing/Page/PromoSanTokenBanner.svelte
> +      full PRO access.<br />
Next a should be in the next line.

2022-10-07 10:58 UTC, DmitriVanGuard requested changes

2022-10-07 10:58 UTC, DmitriVanGuard commented on src/ui/Pricing/Page/sanTokenBanner.svg
> +      fill="var(--orange-hover, #FD9317)"
CSS variables are not needed

2022-10-07 10:58 UTC, DmitriVanGuard commented on src/ui/Pricing/Page/PromoSanTokenBanner.svelte
> +  }
Change the margin in the component file `src/ui/Pricing/Page/Plans.svelte`

2022-10-07 10:58 UTC, DmitriVanGuard commented on src/ui/Pricing/Page/PromoSanTokenBanner.svelte
> +  let className = ''
Missing new line

2022-10-07 10:58 UTC, DmitriVanGuard commented on src/ui/Pricing/Page/PromoSanTokenBanner.svelte
> +<section class="santokenbanner row v-center justify {className}">
1. `santokenbanner` is redundant
2. Add `body-2` and remove it from children

2022-10-07 10:58 UTC, DmitriVanGuard commented on src/ui/Pricing/Page/PromoSanTokenBanner.svelte
> +    border: 1px solid var(--porcelain);
Use `border` class

2022-10-07 10:58 UTC, DmitriVanGuard commented on src/ui/Pricing/Page/PromoSanTokenBanner.svelte
> +        class="btn-0 block"
`row` instead of `block`

2022-10-07 10:58 UTC, DmitriVanGuard commented on src/ui/Pricing/Page/PromoSanTokenBanner.svelte
> +    width: 424px;
Should be responsive

2022-10-07 10:58 UTC, DmitriVanGuard commented on src/ui/Pricing/Page/PromoSanTokenBanner.svelte
> +    a.btn-1 {
Just `.btn-1`

2022-10-07 10:58 UTC, DmitriVanGuard commented on src/ui/Pricing/Page/PromoSanTokenBanner.svelte
> +    }
Please, read again 3rd point of the last review

2022-10-11 11:36 UTC, DmitriVanGuard requested changes

2022-10-11 14:23 UTC, DmitriVanGuard approved these changes

2022-10-11 14:26 UTC, merged